No use toml, just buildSrc directory
kpkpkpk/OneOfTheProject pull request #8
Opened 2022-09-08 14:04 UTC by E1ko0o

Toml файл оставил, но я его не использую, все через папку buildSrc

2022-09-08 19:31 UTC, kpkpkpk requested changes

2022-09-08 19:31 UTC, kpkpkpk commented on settings.gradle.kts
> +    defaultLibrariesExtensionName.set("libs")
кстати, это лишнее, оно тут не нужно

2022-09-08 19:31 UTC, kpkpkpk commented on settings.gradle.kts
> +    defaultLibrariesExtensionName.set("libs")
потому что по дефолту libs имеет название libs

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +kotlin-stdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
а это что вообще, зачем оно

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +glide = "com.github.bumptech.glide:glide:4.12.0"
го coil заюзаем

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation-ktx:1.0.0-alpha03"
а для чего эта штука служит?

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +glide = "com.github.bumptech.glide:glide:4.12.0"
вижу, что ты добавил в зависимости coil, тогда зачем нужен gilde?

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +affectedmoduledetector = "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.1.2"
надеюсь от дропбокса эта штука работает)))

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +affectedmoduledetector = "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.1.2"
если интересно что это и как работает, то посмотри доклад от Максима Щепалина на ютубе

https://www.youtube.com/watch?v=3FCeOL8kgZg&ab_channel=Mobius

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +squareup-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
думаешь точно моки нужны такие?

2022-09-08 19:31 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +squareup-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
wiremock думал заюзать

2022-09-09 06:04 UTC, E1ko0o commented on settings.gradle.kts
> +    defaultLibrariesExtensionName.set("libs")
Согл, убрал 16 строку

2022-09-09 06:05 UTC, E1ko0o commented on gradle/libs.versions.toml
> +glide = "com.github.bumptech.glide:glide:4.12.0"
Убрал Glide

2022-09-09 06:07 UTC, E1ko0o commented on gradle/libs.versions.toml
> +kotlin-stdlibJdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
46-47 убрал: jdk8 не будем поддерживать, она не нужна, а 46 строка дублирует plugin kotlin, прописанный в build.gradle.kts

2022-09-09 06:08 UTC, E1ko0o commented on gradle/libs.versions.toml
> +androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation-ktx:1.0.0-alpha03"
Kotlin extensions for 'dynamicanimation' artifact - убрал

2022-09-09 06:11 UTC, E1ko0o commented on gradle/libs.versions.toml
> +affectedmoduledetector = "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.1.2"
A Gradle Plugin and library to determine which modules were affected in a commit. - вряд-ли мы будем юзать это... Пока оставил, потом скажи, удалять ли

2022-09-09 06:12 UTC, E1ko0o commented on gradle/libs.versions.toml
> +squareup-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
Вообще не знаю, нужен ли нам. Пока оставил, потом скажи, удалять ли

2022-09-09 19:39 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +squareup-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.9.3"
ну мы для таких целей используем WireMock, поэтому я сам если что потом удалю

2022-09-09 19:44 UTC, kpkpkpk approved these changes, later dismissed

2022-09-11 16:27 UTC, kpkpkpk requested changes

2022-09-11 16:27 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +    "androidx-test-uiAutomator", "androidx-test-espressoCore", "androidx-test-espressoWeb",
мы же не будем делать webView, нам не нужон espressoWeb

2022-09-11 16:27 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +    "robolectric", "truth", "junit", "napier", "dokka", "snapper",
зачем так много либ с логгированием? оставь что-то одно на свой вкус

2022-09-11 16:27 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +    "android-tools-lint-tests", "squareup-mockwebserver", "affectedmoduledetector",
affectedmoduledetector мы же выпилили, разве нет?

2022-09-11 16:27 UTC, kpkpkpk commented on settings.gradle.kts
> +
пустая строка

2022-09-11 16:28 UTC, kpkpkpk requested changes

2022-09-11 16:28 UTC, kpkpkpk commented on gradle/libs.versions.toml
> +coroutines = ["kotlin-coroutines-android", "kotlin-coroutines-test"]
сюда стоит еще добавить coreовские корутины, не только андридовские

2022-09-11 16:36 UTC, E1ko0o commented on settings.gradle.kts
> +
Это плохо?

2022-09-11 16:54 UTC, kpkpkpk commented on settings.gradle.kts
> +
просто нет смысла оставлять ее тут, пусть все будет по красоте)

2022-09-11 16:58 UTC, kpkpkpk approved these changes

2022-09-11 16:59 UTC, merged